# .air.toml for Air v1.63.0+

[build]
# Command to build your Go app
cmd = "go build -o ./tmp/main ."

# Binary output path
bin = "./tmp/main"

# Delay before rebuilding (milliseconds)
delay = 1000

# File extensions to watch
include_ext = ["go", "tpl", "tmpl", "html"]

# Directories to exclude (React client, tmp, node_modules)
exclude_dir = ["tmp", "client", "node_modules"]

# Stop running when build fails
stop_on_error = true

[log]
# Display timestamps and colored output
time = true
color = true

[misc]
# Remove tmp files when Air exits
clean_on_exit = true
